-- Project Euler: Problem 2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


-- Run the function as such: sumEvenFib 0 0 0
sumEvenFib :: Integral a => a -> a -> a -> a
sumEvenFib 0 0 x = sumEvenFib 1 1 0
sumEvenFib f1 f2 x = if f1 > 4000000
                     then x
                     else if even f1
                         then sumEvenFib f2 (f1 + f2) (x + f1)
                         else sumEvenFib f2 (f1 + f2) x